import { useEffect, useState } from 'react'
import Layout from '../../../components/Layout'
import { useAuth } from '../../../lib/useAuth'
import { usePlan } from '../../../lib/usePlan'
import { getProperties, type Property } from '../../../lib/supabase'
import { supabase } from '../../../lib/supabase'
import { FileText, Download, Zap, Shield } from 'lucide-react'
import Link from 'next/link'
import { format, addMonths } from 'date-fns'

type Tenant = { id: string; name: string; email: string; rent_amount: number; start_date: string }

function buildAST(fields: {
  tenantName: string; tenantEmail: string; rentAmount: number;
  landlordName: string; landlordAddress: string; landlordEmail: string;
  propertyAddress: string; startDate: string; termMonths: number;
  rentDay: string; depositAmount: string; depositScheme: string; specialTerms: string;
}) {
  const startDate = new Date(fields.startDate)
  const endDate = addMonths(startDate, fields.termMonths)
  const dayLabel = fields.rentDay === '1' ? '1st' : fields.rentDay === '2' ? '2nd' : fields.rentDay === '3' ? '3rd' : fields.rentDay + 'th'

  const lines = [
    'ASSURED SHORTHOLD TENANCY AGREEMENT',
    '',
    'This agreement is made under the Housing Act 1988 (as amended by the Housing Act 1996 and the Renters Rights Act 2025).',
    '',
    'DATE: ' + format(new Date(), 'd MMMM yyyy'),
    '',
    'PARTIES',
    '-------',
    'LANDLORD: ' + (fields.landlordName || '[Landlord Name]'),
    'ADDRESS:  ' + (fields.landlordAddress || '[Landlord Address]'),
    'EMAIL:    ' + (fields.landlordEmail || '[Landlord Email]'),
    '',
    'TENANT:   ' + fields.tenantName,
    'EMAIL:    ' + (fields.tenantEmail || '[Tenant Email]'),
    '',
    'PROPERTY',
    '--------',
    fields.propertyAddress,
    '',
    'TERM',
    '----',
    'Type:       Fixed term Assured Shorthold Tenancy',
    'Start date: ' + format(startDate, 'd MMMM yyyy'),
    'End date:   ' + format(endDate, 'd MMMM yyyy'),
    'Duration:   ' + fields.termMonths + ' months',
    '',
    'RENT',
    '----',
    'Monthly rent:   £' + (fields.rentAmount || 0).toFixed(2),
    'Payment day:    ' + dayLabel + ' of each month',
    'Payment method: Bank transfer',
    '',
    'DEPOSIT',
    '-------',
    'Deposit amount: £' + (fields.depositAmount || '0.00'),
    'Protection:     ' + fields.depositScheme,
    'Note: The deposit will be protected within 30 days of receipt in a government-approved scheme.',
    '',
    'LANDLORD OBLIGATIONS',
    '--------------------',
    '1. To maintain the structure and exterior of the Property.',
    '2. To keep in repair all installations for gas, electricity, water and sanitation.',
    '3. To ensure the Property meets the Decent Homes Standard.',
    '4. To comply with the Renters Rights Act 2025.',
    '5. To protect the deposit in a government-approved scheme within 30 days.',
    '6. To give at least 4 months notice to end the tenancy.',
    '',
    'TENANT OBLIGATIONS',
    '------------------',
    '1. To pay the rent on time each month.',
    '2. To use the Property as a private dwelling only.',
    '3. Not to sublet without written consent.',
    '4. To keep the Property clean and tidy.',
    '5. To report any disrepair promptly.',
    '6. Not to cause nuisance to neighbours.',
    '7. To allow access for inspections with 24 hours written notice.',
    '',
    'POSSESSION',
    '----------',
    'Section 21 no-fault evictions have been abolished under the Renters Rights Act 2025.',
    'The landlord may only recover possession on valid grounds under Schedule 2 of the Housing Act 1988.',
    '',
  ]

  if (fields.specialTerms) {
    lines.push('SPECIAL TERMS')
    lines.push('-------------')
    lines.push(fields.specialTerms)
    lines.push('')
  }

  lines.push('SIGNATURES')
  lines.push('----------')
  lines.push('LANDLORD: _________________________ DATE: _____________')
  lines.push('          ' + (fields.landlordName || '[Landlord Name]'))
  lines.push('')
  lines.push('TENANT:   _________________________ DATE: _____________')
  lines.push('          ' + fields.tenantName)
  lines.push('')
  lines.push('---')
  lines.push('Generated by LetFlowUK (app.letflowuk.com). Consider legal review for complex situations.')

  return lines.join('\n')
}

export default function AgreementsPage() {
  const { user } = useAuth()
  const { plan } = usePlan()
  const isPro = plan === 'pro'
  const [properties, setProperties] = useState<Property[]>([])
  const [tenants, setTenants] = useState<Tenant[]>([])
  const [tenantId, setTenantId] = useState('')
  const [landlordName, setLandlordName] = useState('')
  const [landlordAddress, setLandlordAddress] = useState('')
  const [landlordEmail, setLandlordEmail] = useState('')
  const [depositAmount, setDepositAmount] = useState('')
  const [depositScheme, setDepositScheme] = useState('DPS')
  const [startDate, setStartDate] = useState(format(new Date(), 'yyyy-MM-dd'))
  const [termMonths, setTermMonths] = useState(12)
  const [rentDay, setRentDay] = useState('1')
  const [specialTerms, setSpecialTerms] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!user) return
    Promise.all([
      getProperties(user.id),
      supabase.from('tenants').select('id,name,email,rent_amount,start_date').eq('landlord_id', user.id).eq('status', 'active')
    ]).then(([props, { data: ts }]) => {
      setProperties(props)
      setTenants(ts || [])
      setLoading(false)
    })
    // Pre-fill landlord name from profile
    supabase.from('profiles').select('landlord_name,notification_email').eq('id', user.id).single()
      .then(({ data }) => {
        if (data?.landlord_name) setLandlordName(data.landlord_name)
        if (data?.notification_email) setLandlordEmail(data.notification_email)
      })
  }, [user])

  const selectedTenant = tenants.find(t => t.id === tenantId)

  const handleGenerate = () => {
    if (!selectedTenant) return
    const text = buildAST({
      tenantName: selectedTenant.name,
      tenantEmail: selectedTenant.email || '',
      rentAmount: selectedTenant.rent_amount,
      landlordName, landlordAddress, landlordEmail,
      propertyAddress: '[Property Address — edit before printing]',
      startDate, termMonths, rentDay, depositAmount, depositScheme, specialTerms
    })
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'AST-' + selectedTenant.name.replace(/ /g, '-') + '-' + startDate + '.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  if (!isPro) return (
    <Layout>
      <div className="p-4 sm:p-8 max-w-xl">
        <div className="flex items-center gap-3 mb-2">
          <FileText size={22} style={{ color: 'var(--text-primary)' }} />
          <h1 className="text-2xl font-semibold" style={{ color: 'var(--text-primary)' }}>Tenancy Agreements</h1>
        </div>
        <p className="text-sm mb-8" style={{ color: 'var(--text-secondary)' }}>Generate RRA 2025-compliant AST agreements pre-filled with your tenant data.</p>
        <div className="card p-8 text-center">
          <div className="w-12 h-12 bg-gray-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <Zap size={20} className="text-gray-400" />
          </div>
          <h2 className="font-semibold mb-2" style={{ color: 'var(--text-primary)' }}>Pro feature</h2>
          <p className="text-sm mb-6" style={{ color: 'var(--text-secondary)' }}>Generate AST agreements pre-filled with your tenant and property data.</p>
          <Link href="/dashboard/billing" className="btn-primary inline-flex items-center gap-2">
            <Zap size={14} />Upgrade to Pro
          </Link>
        </div>
      </div>
    </Layout>
  )

  return (
    <Layout>
      <div className="p-4 sm:p-8 max-w-2xl">
        <div className="flex items-center gap-3 mb-1">
          <FileText size={22} style={{ color: 'var(--text-primary)' }} />
          <h1 className="text-2xl font-semibold" style={{ color: 'var(--text-primary)' }}>Tenancy Agreements</h1>
        </div>
        <p className="text-sm mb-6" style={{ color: 'var(--text-secondary)' }}>Generate an RRA 2025-compliant AST pre-filled with your tenant data.</p>

        <div className="card p-6 space-y-4">
          <div>
            <label className="label">Tenant</label>
            <select className="input" value={tenantId} onChange={e => setTenantId(e.target.value)}>
              <option value="">Select tenant...</option>
              {tenants.map(t => <option key={t.id} value={t.id}>{t.name} — £{t.rent_amount}/mo</option>)}
            </select>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="label">Your full name</label>
              <input className="input" placeholder="e.g. Luke Walker" value={landlordName} onChange={e => setLandlordName(e.target.value)} />
            </div>
            <div>
              <label className="label">Your email</label>
              <input className="input" type="email" placeholder="you@email.com" value={landlordEmail} onChange={e => setLandlordEmail(e.target.value)} />
            </div>
          </div>

          <div>
            <label className="label">Your address</label>
            <input className="input" placeholder="Your correspondence address" value={landlordAddress} onChange={e => setLandlordAddress(e.target.value)} />
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <div>
              <label className="label">Start date</label>
              <input type="date" className="input" value={startDate} onChange={e => setStartDate(e.target.value)} />
            </div>
            <div>
              <label className="label">Term</label>
              <select className="input" value={termMonths} onChange={e => setTermMonths(Number(e.target.value))}>
                <option value={6}>6 months</option>
                <option value={12}>12 months</option>
                <option value={24}>24 months</option>
              </select>
            </div>
            <div>
              <label className="label">Rent due</label>
              <select className="input" value={rentDay} onChange={e => setRentDay(e.target.value)}>
                {[1,5,7,10,15,20,25,28].map(d => <option key={d} value={String(d)}>{d}{d===1?'st':d===2?'nd':d===3?'rd':'th'}</option>)}
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="label">Deposit (£)</label>
              <input type="number" className="input" placeholder={selectedTenant ? String(Math.round(selectedTenant.rent_amount * 5 / 4)) : 'e.g. 625'} value={depositAmount} onChange={e => setDepositAmount(e.target.value)} />
            </div>
            <div>
              <label className="label">Deposit scheme</label>
              <select className="input" value={depositScheme} onChange={e => setDepositScheme(e.target.value)}>
                <option value="DPS">DPS</option>
                <option value="TDS">TDS</option>
                <option value="MyDeposits">MyDeposits</option>
              </select>
            </div>
          </div>

          <div>
            <label className="label">Special terms (optional)</label>
            <textarea className="input" rows={2} placeholder="e.g. No pets. Parking space included." value={specialTerms} onChange={e => setSpecialTerms(e.target.value)} />
          </div>

          <button onClick={handleGenerate} disabled={!tenantId || !landlordName} className="btn-primary w-full flex items-center justify-center gap-2">
            <Download size={16} />Generate & Download AST
          </button>
          <div className="flex items-start gap-2 p-3 rounded-xl text-xs" style={{ background: 'var(--color-background-secondary)', color: 'var(--text-muted)' }}>
            <Shield size={12} className="flex-shrink-0 mt-0.5" />
            <span>Downloads as a .txt file ready to print and sign. Consider legal review for complex situations.</span>
          </div>
        </div>
      </div>
    </Layout>
  )
}